# Build and Package Bibneat Studio Electron App

name: Build and Package Electron App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install extra deps
        run: sudo apt-get install -y build-essential curl flatpak-builder elfutils dpkg fakeroot rpm zip
      - name: Make flatpak happy
        run: flatpak --user remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      - name: Install dependencies
        working-directory: './electron-app'
        run: npm ci
      - name: Build and package
        working-directory: './electron-app'
        run: npm run make
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: bibneat-studio-ubuntu-flatpack
          path: electron-app/out/make
